package com.arviona.controller;

import com.arviona.exception.BadRequestException;
import com.arviona.model.*;
import com.arviona.repository.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
@RequestMapping("/api/v1/teacher-copilot")
@PreAuthorize("hasRole('TEACHER')")
public class TeacherCopilotController {

    @Autowired
    private ClassRepository classRepository;

    @Autowired
    private QuestRepository questRepository;

    @Autowired
    private BossBattleRepository bossBattleRepository;

    @PostMapping("/upload")
    public ResponseEntity<?> uploadCopilot(
            @RequestBody Map<String, String> payload) {
        
        String classId = payload.get("classId");
        String fileText = payload.get("fileText");

        if (classId == null || fileText == null || fileText.trim().isEmpty()) {
            throw new BadRequestException("ClassId and document content cannot be empty");
        }

        ClassEntity classEntity = classRepository.findById(classId)
                .orElseThrow(() -> new BadRequestException("Class not found"));

        // Extract a mock title from the first line or use default
        String firstLine = fileText.split("\n")[0].trim();
        String title = firstLine.length() > 50 ? firstLine.substring(0, 47) + "..." : firstLine;
        if (title.isEmpty()) {
            title = "Dynamic Module";
        }

        // Generate Quest
        String questId = UUID.randomUUID().toString();
        Quest quest = Quest.builder()
                .id(questId)
                .classEntity(classEntity)
                .title("Quest: " + title)
                .description("Automated quest generated by Teacher Copilot from: " + title)
                .rewardXp(150)
                .questDataJson("{\"steps\":[\"Read the uploaded summary\",\"Solve practice problems 1-5\",\"Submit analysis essay\"]}")
                .chainName("Copilot Discoveries")
                .createdBy("teacher-copilot")
                .build();
        questRepository.save(quest);

        // Generate Boss Battle
        String battleId = UUID.randomUUID().toString();
        BossBattle battle = BossBattle.builder()
                .id(battleId)
                .classId(classId)
                .title("Boss Battle: " + title)
                .subject("General")
                .timeLimitMins(20)
                .xpReward(300)
                .coinsReward(100)
                .totalQuestions(10)
                .difficulty("HARD")
                .active(true)
                .createdBy("teacher-copilot")
                .build();
        bossBattleRepository.save(battle);

        Map<String, Object> response = new HashMap<>();
        response.put("message", "Teacher Copilot successfully processed content!");
        response.put("generatedQuestId", questId);
        response.put("generatedQuestTitle", quest.getTitle());
        response.put("generatedBossBattleId", battleId);
        response.put("generatedBossBattleTitle", battle.getTitle());

        return ResponseEntity.ok(response);
    }
}
